#!/bin/bash

PGVER="13"
PGDATA="/var/lib/pgsql/data"

V_214080(){
    local NAME="V-214080"
    local DESCRIPTION="PostgreSQL must utilize centralized management of the content captured in audit records generated by all components of PostgreSQL"
    local SEVERITY="MEDIUM"
    local SCORE=""
    local DONE="0"

    echo -e "${YELLOW}[!] Checking PostgreSQL log configuration...${RESET}"
    log_destination=$(sudo -u postgres psql -t -c "SHOW log_destination" | tr -d '[:space:]')
    syslog_facility=$(sudo -u postgres psql -t -c "SHOW syslog_facility" | tr -d '[:space:]')

    fix_needed=false

    if [[ "$log_destination" != "syslog" ]]; then
        echo -e "${RED}[!] Log destination is not set to syslog.${RESET}"
        fix_needed=true
    else
        echo -e "${GREEN}[+] Log destination is correctly set to syslog.${RESET}"
    fi

    if [[ -z "$syslog_facility" || "$syslog_facility" == "none"  ]]; then
        echo -e "${RED}[!] Syslog facility is not configured.${RESET}"
        fix_needed=true
    fi

    if [[ "$fix_needed" == true  ]]; then
        echo -e "${YELLOW}[*] Applying fixes to PostgreSQL configuration...${RESET}"
        sudo -u postgres bash -c "
            echo \"Modifying postgresql.conf...\"
            sed -i \"s/^#*log_destination.*/log_destination = 'syslog'/\" ${PGDATA}/postgresql.conf
            sed -i \"s/^#*syslog_facility.*/syslog_facility = 'LOCAL0'/\" ${PGDATA}/postgresql.conf
            sed -i \"s/^#*syslog_ident.*/syslog_ident = 'postgres'/\" ${PGDATA}/postgresql.conf
        "

        ## postgresql.service
        sudo systemctl reload postgresql.service

        DONE="1"
        vulnerabilities+=("$NAME|$DESCRIPTION|$SEVERITY|$SCORE|$DONE")
    fi
}
